/*
 * Automatically generated by png2c
 *
 * $Id: printer_image.h 49501 2014-08-21 18:42:23Z mazze $
 */


extern unsigned long Printer[];
#define PRINTER_WIDTH 120
#define PRINTER_HEIGHT 110
#define PRINTER_DEPTH 32
