# MakeFile für Updater MUI module
# $Date: 2013-12-01 23:08:26 +0100 (Sun, 01 Dec 2013) $
# $Revision: 48481 $

#####################################################################

# Updater.module cannot be built with SAS/C

include		makefile-new

