# makefile für sqlite3.ibrary (C-Version)
# $Date: 2013-12-01 23:08:26 +0100 (Sun, 01 Dec 2013) $
# $Revision: 48481 $

# sqlite3.library cannot be built with SAS/C due to lack of 64-bit integers.

include		makefile-new

